name: terraform-gcp

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: true

jobs:
  plan:
    runs-on: ubuntu-latest
    # no "if" here â†’ runs for both pull_request and push to main
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.x"

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Who am I (debug)
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "ADC file:"
          cat $HOME/.config/gcloud/application_default_credentials.json || echo "NO ADC FILE FOUND"
          echo ""
          echo "gcloud auth list:"
          gcloud auth list

      - name: Terraform init
        run: terraform init

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan.binary

      - name: Terraform show (json)
        run: terraform show -json tfplan.binary > tfplan.json

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: |
            tfplan.binary
            tfplan.json

  apply:
    runs-on: ubuntu-latest
    needs: plan                       # ensures "apply" runs right after "plan"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.x"

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Who am I (debug)
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "ADC file:"
          cat $HOME/.config/gcloud/application_default_credentials.json || echo "NO ADC FILE FOUND"
          echo ""
          echo "gcloud auth list:"
          gcloud auth list

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply tfplan.binary